language: python

python:
  - "3.6"

install:
  - apt install python3 python3-dev libffi-dev libssl-dev
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov

script:
  - pytest tests/

after_success:
  - codecov
