language: python

python:
  - "3.6"

install:
  - sudo git clone https://github.com/aleaxit/gmpy.git
  - cd gmpy && sudo python3 setup.py install && cd ..
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov

script:
  - pytest tests/ --cov

after_success:
  - codecov
