language: python

python:
  - "3.6"

install:
  - sudo apt install python3 python3-dev
  - sudo apt install libffi-dev libssl-dev libgmp-dev libmpfr-dev libmpc-dev
  - sudo pip install -r requirements.txt
  - sudo pip install -r dev-requirements.txt
  - sudo pip install codecov

script:
  # - pytest tests/

after_success:
  - codecov
