language: python

python:
  - "3.6"

install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  - pip install -r requirements.txt
  - pip install pytest && pip install pytest-cov
  - pip install codecov

script:
  - pytest tests/ --cov

after_success:
  - codecov
