language: python

python:
  - "3.6"

install:
  - sudo apt-get update -y
  - sudo apt-get install build-essential libssl-dev libffi-dev python3-dev
  - sudo pip install -r requirements.txt
  - sudo pip install -r dev-requirements.txt
  - sudo pip install codecov

script:
  - pytest tests/

after_success:
  - codecov
