language: python

python:
  - "3.6"

install:
  - sudo pip install -r requirements.txt
  - sudo pip install -r dev-requirements.txt
  - sudo pip install codecov

script:
  - pytest tests/

after_success:
  - codecov
