#!/usr/bin/env python3

"""
Zeus Demo Election
"""

import sys
import argparse
from tests.election.makers import mk_election

if __name__ == '__main__':
    prog = sys.argv[0]

    usage = '%s [--mixes=...]' % prog
    description = 'Zeus Demo Election'
    epilog = '\n'
    parser = argparse.ArgumentParser(prog=prog,
                        usage=usage,
                        description=__doc__,
                        epilog=epilog)

    parser.add_argument('--mixes',
                        type=int, default=3, dest='nr_mixes',
                        help="Number of times to mix")

    args = parser.parse_args()
    nr_mixes = args.nr_mixes

    mk_election(nr_mixes=nr_mixes).run()

    #
    # # Abortions
    #
    # from tests.election.emulators.election_configs import (
    #     config_1, config_2, config_3, config_4, config_5, config_6)
    # mk_election(config=config_2, nr_mixes=nr_mixes).run()
    # mk_election(config=config_3, nr_mixes=nr_mixes).run()
    # mk_election(config=config_4, nr_mixes=nr_mixes).run()
    # mk_election(config=config_5, nr_mixes=nr_mixes).run()
    # mk_election(config=config_6, nr_mixes=nr_mixes).run()
